export const BOT_TITLE = "финансы";

export const BUTTONS = {
  start: "начать",
  skip: "пропустить",
  next: "дальше",
  back: "назад",
  toMain: "на главную",
  main: "главная",
  income: "доход",
  expense: "расход",
  operations: "операции",
  report: "отчёт",
  categories: "категории",
  settings: "настройки",
  howToUse: "как пользоваться",
  draft: "черновик",
  continue: "продолжить",
  delete: "удалить",
  save: "сохранить",
  edit: "изменить",
  search: "поиск",
  enterQuery: "ввести запрос",
  today: "сегодня",
  yesterday: "вчера",
  week: "неделя",
  month: "месяц",
  year: "год",
  allTime: "всё время",
  customPeriod: "свой период",
  multipleSelect: "выбрать несколько",
  newSearch: "новый поиск",
  toResults: "к результатам",
  transfer: "перенести",
  transferAllEntries: "перенести все записи",
  removeSubcategory: "снять подкатегорию",
  cancel: "отмена",
  expenseBreakdown: "по расходам",
  incomeBreakdown: "по доходам",
  allEntries: "все записи",
  anotherPeriod: "другой период",
  expenseCategories: "расходы",
  incomeCategories: "доходы",
  addCategory: "+ категория",
  hidden: "скрытые",
  addSubcategory: "+ подкатегория",
  hide: "скрыть",
  restore: "вернуть",
  currency: "валюта",
  time: "время",
  subcategories: "подкатегории",
  quickAccess: "быстрый доступ",
  sorting: "сортировка",
  data: "данные",
  ruble: "₽ рубль",
  dollar: "$ доллар",
  euro: "€ евро",
  another: "другая",
  enable: "включить",
  disable: "выключить",
  automatically: "автоматически",
  own: "свои",
  off: "выключен",
  done: "готово",
  resetToGeneral: "сбросить к общему",
  forThisBot: "для этого бота",
  forOtherApps: "в другие приложения",
  resetSettings: "сбросить настройки",
  clearAll: "очистить всё",
  saveToFile: "сохранить в файл",
  loadFromFile: "загрузить из файла",
  merge: "объединить",
  addAll: "добавить всё",
  fix: "исправить",
  moveData: "перенести данные",
  searchThis: "искать это",
  toNewEntries: "в новые записи",
  chooseAll: "выбрать все",
  changeTime: "изменить время"
  ,
  withoutSubcategory: "без подкатегории"
} as const;

export const ONBOARDING_TEXTS = [
  "Бот помогает вести доходы и расходы, искать старые записи, смотреть отчёты и переносить записи из других приложений.",
  "Добавлять можно по шагам кнопками или одним сообщением.",
  "Текстовый ввод должен быть быстрым и живым.\n\nПримеры:\n-450 продукты пятёрочка хлеб\n+4000 зарплата премия\n-120 транспорт метро",
  "Если бот понял запись не до конца, он сам уточнит только недостающее.",
  "Любую запись потом можно найти, исправить, перенести в другую категорию или удалить.",
  "Есть поиск, отчёты, категории и подкатегории.",
  "Если записи уже есть в другом приложении, их можно перенести сюда. Если нет — можно просто пойти дальше."
] as const;

export function onboardingProgress(step: number): string {
  return new Array(7).fill("○").map((item, index) => (index <= step ? "●" : item)).join(" ");
}
