export const BOT_TITLE = "финансы";

export const BUTTONS = {
  start: "начать",
  skip: "пропустить",
  next: "дальше",
  back: "назад",
  toMain: "на главную",
  main: "главная",
  income: "доход",
  expense: "расход",
  operations: "операции",
  report: "отчёт",
  categories: "категории",
  settings: "настройки",
  howToUse: "как пользоваться",
  draft: "черновик",
  continue: "продолжить",
  delete: "удалить",
  save: "сохранить",
  edit: "изменить",
  search: "поиск",
  enterQuery: "ввести запрос",
  today: "сегодня",
  yesterday: "вчера",
  week: "неделя",
  month: "месяц",
  year: "год",
  allTime: "всё время",
  customPeriod: "свой период",
  multipleSelect: "выбрать несколько",
  newSearch: "новый поиск",
  toResults: "к результатам",
  transfer: "перенести",
  transferAllEntries: "перенести все записи",
  removeSubcategory: "снять подкатегорию",
  cancel: "отмена",
  expenseBreakdown: "по расходам",
  incomeBreakdown: "по доходам",
  allEntries: "все записи",
  anotherPeriod: "другой период",
  expenseCategories: "расходы",
  incomeCategories: "доходы",
  addCategory: "+ категория",
  hidden: "скрытые",
  addSubcategory: "+ подкатегория",
  hide: "скрыть",
  restore: "вернуть",
  currency: "валюта",
  time: "время",
  subcategories: "подкатегории",
  quickAccess: "быстрый доступ",
  sorting: "сортировка",
  data: "данные",
  ruble: "₽ рубль",
  dollar: "$ доллар",
  euro: "€ евро",
  another: "другая",
  enable: "включить",
  disable: "выключить",
  automatically: "автоматически",
  own: "свои",
  off: "выключен",
  done: "готово",
  resetToGeneral: "сбросить к общему",
  forThisBot: "для этого бота",
  forOtherApps: "в другие приложения",
  resetSettings: "сбросить настройки",
  clearAll: "очистить всё",
  saveToFile: "сохранить в файл",
  loadFromFile: "загрузить из файла",
  merge: "объединить",
  addAll: "добавить всё",
  fix: "исправить",
  moveData: "перенести данные",
  searchThis: "искать это",
  toNewEntries: "в новые записи",
  chooseAll: "выбрать все",
  changeTime: "изменить время",
  withoutSubcategory: "без подкатегории",
  allCategories: "все категории",
  allSubcategories: "все подкатегории",
  open: "открыть",
  yesDelete: "да, удалить",
  leaveWithoutSave: "выйти без сохранения",
  stay: "остаться",
  dateTime: "дата и время"
  ,
  show: "показать",
  sendLocation: "отправить геопозицию",
  reset: "сбросить",
  yesReset: "да, сбросить",
  yesDisable: "да, выключить",
  chooseCategory: "выбрать категорию",
  allCategoriesScope: "во всех категориях",
  oneCategoryScope: "в одной категории",
  resetAll: "сбросить всё",
  yesResetAll: "да, сбросить",
  uploadToBot: "загрузить в бот",
  yesUpload: "да, загрузить",
  yesAdd: "да, добавить",
  addNoun: "добавить",
  yesAddAll: "да, добавить всё",
  yesClearAll: "да, очистить всё",
  exit: "выйти",
  yesRemoveSubcategory: "да, снять"
  ,
  yesHide: "да, скрыть",
  yesRestore: "да, вернуть",
  thisMonth: "этот месяц",
  thisYear: "этот год"
} as const;

export const ONBOARDING_TEXTS = [
  "привет\n\nя помогу удобно вести\nдоходы и расходы\n\nздесь можно быстро добавлять записи,\nискать старые,\nсмотреть отчёты\nи переносить записи\nиз других приложений",
  "добавлять можно по-разному\n\nесть два простых способа:\n\n1. по шагам кнопками\n2. одним сообщением текстом\n\nможно выбрать тот,\nкоторый удобнее именно тебе",
  "текстом — это быстро\n\nнапример так:\n\n-450 продукты пятёрочка хлеб\n+4000 зарплата премия\n-120 транспорт метро\n\nможно отправлять по одной записи\nили сразу несколько",
  "можно не переживать о формате\n\nесли бот поймёт запись не до конца,\nон сам уточнит только то,\nчего не хватает\n\nне обязательно заполнять всё\nидеально с первого раза",
  "всё остаётся под рукой\n\nлюбую запись потом можно:\nнайти,\nисправить,\nперенести в другую категорию\nили удалить\n\nесли записей станет много,\nих всё равно будет легко разобрать",
  "бот помогает не только записывать\n\nздесь есть:\nпоиск по сумме, дате и тексту\nотчёты за день, месяц\nили любой свой период\nкатегории и подкатегории\nдля удобного порядка",
  "можно начать не с нуля\n\nесли записи уже есть\nв другом приложении,\nих можно перенести сюда\n\nа если хочешь начать с чистого листа,\nможно просто перейти дальше"
] as const;

export function onboardingProgress(step: number): string {
  return new Array(7).fill("○").map((item, index) => (index <= step ? "●" : item)).join(" ");
}
